export type Country = {
  name: string;
  value: string;
};

export const countries: Country[] = [
  { name: 'Andorra', value: 'AD' },
  { name: 'United Arab Emirates', value: 'AE' },
  { name: 'Afghanistan', value: 'AF' },
  { name: 'Antigua and Barbuda', value: 'AG' },
  { name: 'Anguilla', value: 'AI' },
  { name: 'Albania', value: 'AL' },
  { name: 'Armenia', value: 'AM' },
  { name: 'Angola', value: 'AO' },
  { name: 'Antarctica', value: 'AQ' },
  { name: 'Argentina', value: 'AR' },
  { name: 'American Samoa', value: 'AS' },
  { name: 'Austria', value: 'AT' },
  { name: 'Australia', value: 'AU' },
  { name: 'Aruba', value: 'AW' },
  { name: 'Åland Islands', value: 'AX' },
  { name: 'Azerbaijan', value: 'AZ' },
  { name: 'Bosnia and Herzegovina', value: 'BA' },
  { name: 'Barbados', value: 'BB' },
  { name: 'Bangladesh', value: 'BD' },
  { name: 'Belgium', value: 'BE' },
  { name: 'Burkina Faso', value: 'BF' },
  { name: 'Bulgaria', value: 'BG' },
  { name: 'Bahrain', value: 'BH' },
  { name: 'Burundi', value: 'BI' },
  { name: 'Benin', value: 'BJ' },
  { name: 'Saint Barthélemy', value: 'BL' },
  { name: 'Bermuda', value: 'BM' },
  { name: 'Brunei Darussalam', value: 'BN' },
  { name: 'Bolivia (Plurinational State of)', value: 'BO' },
  { name: 'Bonaire, Sint Eustatius and Saba', value: 'BQ' },
  { name: 'Brazil', value: 'BR' },
  { name: 'Bahamas', value: 'BS' },
  { name: 'Bhutan', value: 'BT' },
  { name: 'Bouvet Island', value: 'BV' },
  { name: 'Botswana', value: 'BW' },
  { name: 'Belarus', value: 'BY' },
  { name: 'Belize', value: 'BZ' },
  { name: 'Canada', value: 'CA' },
  { name: 'Cocos (Keeling) Islands', value: 'CC' },
  { name: 'Congo (the Democratic Republic of the)', value: 'CD' },
  { name: 'Central African Republic', value: 'CF' },
  { name: 'Congo', value: 'CG' },
  { name: 'Switzerland', value: 'CH' },
  { name: "Côte d'Ivoire", value: 'CI' },
  { name: 'Cook Islands', value: 'CK' },
  { name: 'Chile', value: 'CL' },
  { name: 'Cameroon', value: 'CM' },
  { name: 'China', value: 'CN' },
  { name: 'Colombia', value: 'CO' },
  { name: 'Costa Rica', value: 'CR' },
  { name: 'Cuba', value: 'CU' },
  { name: 'Cabo Verde', value: 'CV' },
  { name: 'Curaçao', value: 'CW' },
  { name: 'Christmas Island', value: 'CX' },
  { name: 'Cyprus', value: 'CY' },
  { name: 'Czechia', value: 'CZ' },
  { name: 'Germany', value: 'DE' },
  { name: 'Djibouti', value: 'DJ' },
  { name: 'Denmark', value: 'DK' },
  { name: 'Dominica', value: 'DM' },
  { name: 'Dominican Republic', value: 'DO' },
  { name: 'Algeria', value: 'DZ' },
  { name: 'Ecuador', value: 'EC' },
  { name: 'Estonia', value: 'EE' },
  { name: 'Egypt', value: 'EG' },
  { name: 'Western Sahara', value: 'EH' },
  { name: 'Eritrea', value: 'ER' },
  { name: 'Spain', value: 'ES' },
  { name: 'Ethiopia', value: 'ET' },
  { name: 'Finland', value: 'FI' },
  { name: 'Fiji', value: 'FJ' },
  { name: 'Falkland Islands [Malvinas]', value: 'FK' },
  { name: 'Micronesia (Federated States of)', value: 'FM' },
  { name: 'Faroe Islands', value: 'FO' },
  { name: 'France', value: 'FR' },
  { name: 'Gabon', value: 'GA' },
  { name: 'United Kingdom', value: 'GB' },
  { name: 'United States', value: 'US' },
  { name: 'Grenada', value: 'GD' },
  { name: 'Georgia', value: 'GE' },
  { name: 'French Guiana', value: 'GF' },
  { name: 'Guernsey', value: 'GG' },
  { name: 'Ghana', value: 'GH' },
  { name: 'Gibraltar', value: 'GI' },
  { name: 'Greenland', value: 'GL' },
  { name: 'Gambia', value: 'GM' },
  { name: 'Guinea', value: 'GN' },
  { name: 'Guadeloupe', value: 'GP' },
  { name: 'Equatorial Guinea', value: 'GQ' },
  { name: 'Greece', value: 'GR' },
  { name: 'South Georgia and the South Sandwich Islands', value: 'GS' },
  { name: 'Guatemala', value: 'GT' },
  { name: 'Guam', value: 'GU' },
  { name: 'Guinea-Bissau', value: 'GW' },
  { name: 'Guyana', value: 'GY' },
  { name: 'Hong Kong', value: 'HK' },
  { name: 'Heard Island and McDonald Islands', value: 'HM' },
  { name: 'Honduras', value: 'HN' },
  { name: 'Croatia', value: 'HR' },
  { name: 'Haiti', value: 'HT' },
  { name: 'Hungary', value: 'HU' },
  { name: 'Indonesia', value: 'ID' },
  { name: 'Ireland', value: 'IE' },
  { name: 'Israel', value: 'IL' },
  { name: 'Isle of Man', value: 'IM' },
  { name: 'India', value: 'IN' },
  { name: 'British Indian Ocean Territory', value: 'IO' },
  { name: 'Iraq', value: 'IQ' },
  { name: 'Iran (Islamic Republic of)', value: 'IR' },
  { name: 'Iceland', value: 'IS' },
  { name: 'Italy', value: 'IT' },
  { name: 'Jersey', value: 'JE' },
  { name: 'Jamaica', value: 'JM' },
  { name: 'Jordan', value: 'JO' },
  { name: 'Japan', value: 'JP' },
  { name: 'Kenya', value: 'KE' },
  { name: 'Kyrgyzstan', value: 'KG' },
  { name: 'Cambodia', value: 'KH' },
  { name: 'Kiribati', value: 'KI' },
  { name: 'Comoros', value: 'KM' },
  { name: 'Saint Kitts and Nevis', value: 'KN' },
  { name: "Korea (Democratic People's Republic of)", value: 'KP' },
  { name: 'Korea (Republic of)', value: 'KR' },
  { name: 'Kuwait', value: 'KW' },
  { name: 'Cayman Islands', value: 'KY' },
  { name: 'Kazakhstan', value: 'KZ' },
  { name: "Lao People's Democratic Republic", value: 'LA' },
  { name: 'Lebanon', value: 'LB' },
  { name: 'Saint Lucia', value: 'LC' },
  { name: 'Liechtenstein', value: 'LI' },
  { name: 'Sri Lanka', value: 'LK' },
  { name: 'Liberia', value: 'LR' },
  { name: 'Lesotho', value: 'LS' },
  { name: 'Lithuania', value: 'LT' },
  { name: 'Luxembourg', value: 'LU' },
  { name: 'Latvia', value: 'LV' },
  { name: 'Libya', value: 'LY' },
  { name: 'Morocco', value: 'MA' },
  { name: 'Monaco', value: 'MC' },
  { name: 'Moldova (Republic of)', value: 'MD' },
  { name: 'Montenegro', value: 'ME' },
  { name: 'Saint Martin (French part)', value: 'MF' },
  { name: 'Madagascar', value: 'MG' },
  { name: 'Marshall Islands', value: 'MH' },
  { name: 'Macedonia (the former Yugoslav Republic of)', value: 'MK' },
  { name: 'Mali', value: 'ML' },
  { name: 'Myanmar', value: 'MM' },
  { name: 'Mongolia', value: 'MN' },
  { name: 'Macao', value: 'MO' },
  { name: 'Northern Mariana Islands', value: 'MP' },
  { name: 'Martinique', value: 'MQ' },
  { name: 'Mauritania', value: 'MR' },
  { name: 'Montserrat', value: 'MS' },
  { name: 'Malta', value: 'MT' },
  { name: 'Mauritius', value: 'MU' },
  { name: 'Maldives', value: 'MV' },
  { name: 'Malawi', value: 'MW' },
  { name: 'Mexico', value: 'MX' },
  { name: 'Malaysia', value: 'MY' },
  { name: 'Mozambique', value: 'MZ' },
  { name: 'Namibia', value: 'NA' },
  { name: 'New Caledonia', value: 'NC' },
  { name: 'Niger', value: 'NE' },
  { name: 'Norfolk Island', value: 'NF' },
  { name: 'Nigeria', value: 'NG' },
  { name: 'Nicaragua', value: 'NI' },
  { name: 'Netherlands', value: 'NL' },
  { name: 'Norway', value: 'NO' },
  { name: 'Nepal', value: 'NP' },
  { name: 'Nauru', value: 'NR' },
  { name: 'Niue', value: 'NU' },
  { name: 'New Zealand', value: 'NZ' },
];
