type Language = {
  value: string;
  label: string;
};

export const language: Language[] = [
  { value: 'aa', label: 'Afar' },
  { value: 'ab', label: 'Abkhazian' },
  { value: 'ae', label: 'Avestan' },
  { value: 'af', label: 'Afrikaans' },
  { value: 'ak', label: 'Akan' },
  { value: 'am', label: 'Amharic' },
  { value: 'an', label: 'Aragonese' },
  { value: 'ar-ae', label: 'Arabic (U.A.E.)' },
  { value: 'ar-bh', label: 'Arabic (Bahrain)' },
  { value: 'ar-dz', label: 'Arabic (Algeria)' },
  { value: 'ar-eg', label: 'Arabic (Egypt)' },
  { value: 'ar-iq', label: 'Arabic (Iraq)' },
  { value: 'ar-jo', label: 'Arabic (Jordan)' },
  { value: 'ar-kw', label: 'Arabic (Kuwait)' },
  { value: 'ar-lb', label: 'Arabic (Lebanon)' },
  { value: 'ar-ly', label: 'Arabic (Libya)' },
  { value: 'ar-ma', label: 'Arabic (Morocco)' },
  { value: 'ar-om', label: 'Arabic (Oman)' },
  { value: 'ar-qa', label: 'Arabic (Qatar)' },
  { value: 'ar-sa', label: 'Arabic (Saudi Arabia)' },
  { value: 'ar-sy', label: 'Arabic (Syria)' },
  { value: 'ar-tn', label: 'Arabic (Tunisia)' },
  { value: 'ar-ye', label: 'Arabic (Yemen)' },
  { value: 'ar', label: 'Arabic' },
  { value: 'as', label: 'Assamese' },
  { value: 'av', label: 'Avaric' },
  { value: 'ay', label: 'Aymara' },
  { value: 'az', label: 'Azeri' },
  { value: 'ba', label: 'Bashkir' },
  { value: 'be', label: 'Belarusian' },
  { value: 'bg', label: 'Bulgarian' },
  { value: 'bh', label: 'Bihari' },
  { value: 'bi', label: 'Bislama' },
  { value: 'bm', label: 'Bambara' },
  { value: 'bn', label: 'Bengali' },
  { value: 'bo', label: 'Tibetan' },
  { value: 'br', label: 'Breton' },
  { value: 'bs', label: 'Bosnian' },
  { value: 'ca', label: 'Catalan' },
  { value: 'ce', label: 'Chechen' },
  { value: 'ch', label: 'Chamorro' },
  { value: 'co', label: 'Corsican' },
  { value: 'cr', label: 'Cree' },
  { value: 'cs', label: 'Czech' },
  { value: 'cu', label: 'Church Slavonic' },
  { value: 'cv', label: 'Chuvash' },
  { value: 'cy', label: 'Welsh' },
  { value: 'da', label: 'Danish' },
  { value: 'de-at', label: 'German (Austria)' },
  { value: 'de-ch', label: 'German (Switzerland)' },
  { value: 'de-de', label: 'German (Germany)' },
  { value: 'de-li', label: 'German (Liechtenstein)' },
  { value: 'de-lu', label: 'German (Luxembourg)' },
  { value: 'de', label: 'German' },
  { value: 'dv', label: 'Divehi' },
  { value: 'dz', label: 'Bhutani' },
  { value: 'ee', label: 'Ewe' },
  { value: 'el', label: 'Greek' },
  { value: 'en-au', label: 'English (Australia)' },
  { value: 'en-bz', label: 'English (Belize)' },
  { value: 'en-ca', label: 'English (Canada)' },
  { value: 'en-cb', label: 'English (Caribbean)' },
  { value: 'en-gb', label: 'English (United Kingdom)' },
  { value: 'en-ie', label: 'English (Ireland)' },
  { value: 'en-jm', label: 'English (Jamaica)' },
  { value: 'en-nz', label: 'English (New Zealand)' },
  { value: 'en-ph', label: 'English (Philippines)' },
  { value: 'en-tt', label: 'English (Trinidad and Tobago)' },
  { value: 'en-us', label: 'English (United States)' },
  { value: 'en-za', label: 'English (South Africa)' },
  { value: 'en-zw', label: 'English (Zimbabwe)' },
  { value: 'en', label: 'English' },
  { value: 'eo', label: 'Esperanto' },
  { value: 'es-ar', label: 'Spanish (Argentina)' },
  { value: 'es-bo', label: 'Spanish (Bolivia)' },
  { value: 'es-cl', label: 'Spanish (Chile)' },
  { value: 'es-co', label: 'Spanish (Colombia)' },
  { value: 'es-cr', label: 'Spanish (Costa Rica)' },
  { value: 'es-do', label: 'Spanish (Dominican Republic)' },
  { value: 'es-ec', label: 'Spanish (Ecuador)' },
  { value: 'es-es', label: 'Spanish (Spain)' },
  { value: 'es-gt', label: 'Spanish (Guatemala)' },
  { value: 'es-hn', label: 'Spanish (Honduras)' },
  { value: 'es-mx', label: 'Spanish (Mexico)' },
  { value: 'es-ni', label: 'Spanish (Nicaragua)' },
  { value: 'es-pa', label: 'Spanish (Panama)' },
  { value: 'es-pe', label: 'Spanish (Peru)' },
  { value: 'es-pr', label: 'Spanish (Puerto Rico)' },
  { value: 'es-py', label: 'Spanish (Paraguay)' },
  { value: 'es-sv', label: 'Spanish (El Salvador)' },
  { value: 'es-us', label: 'Spanish (United States)' },
  { value: 'es-uy', label: 'Spanish (Uruguay)' },
  { value: 'es-ve', label: 'Spanish (Venezuela)' },
  { value: 'es', label: 'Spanish' },
  { value: 'et', label: 'Estonian' },
  { value: 'eu', label: 'Basque' },
  { value: 'fa', label: 'Farsi' },
  { value: 'ff', label: 'Fulah' },
  { value: 'fi', label: 'Finnish' },
  { value: 'fj', label: 'Fiji' },
  { value: 'fo', label: 'Faroese' },
  { value: 'fr-be', label: 'French (Belgium)' },
  { value: 'fr-ca', label: 'French (Canada)' },
  { value: 'fr-ch', label: 'French (Switzerland)' },
  { value: 'fr-fr', label: 'French (France)' },
  { value: 'fr-lu', label: 'French (Luxembourg)' },
  { value: 'fr-mc', label: 'French (Monaco)' },
  { value: 'fr', label: 'French' },
  { value: 'fy', label: 'Frisian' },
  { value: 'ga', label: 'Irish' },
  { value: 'gd', label: 'Gaelic' },
  { value: 'gl', label: 'Galician' },
  { value: 'gn', label: 'Guarani' },
  { value: 'gu', label: 'Gujarati' },
  { value: 'gv', label: 'Manx' },
  { value: 'ha', label: 'Hausa' },
  { value: 'he', label: 'Hebrew' },
  { value: 'hi', label: 'Hindi' },
  { value: 'ho', label: 'Hiri Motu' },
  { value: 'hr', label: 'Croatian' },
  { value: 'ht', label: 'Haitian' },
  { value: 'hu', label: 'Hungarian' },
  { value: 'hy', label: 'Armenian' },
  { value: 'hz', label: 'Herero' },
  { value: 'ia', label: 'Interlingua' },
  { value: 'id', label: 'Indonesian' },
  { value: 'ie', label: 'Interlingue' },
  { value: 'ig', label: 'Igbo' },
  { value: 'ii', label: 'Sichuan Yi' },
  { value: 'ik', label: 'Inupiaq' },
  { value: 'io', label: 'Ido' },
  { value: 'is', label: 'Icelandic' },
  { value: 'it-ch', label: 'Italian (Switzerland)' },
  { value: 'it-it', label: 'Italian (Italy)' },
  { value: 'it', label: 'Italian' },
  { value: 'iu', label: 'Inuktitut' },
  { value: 'ja', label: 'Japanese' },
  { value: 'jv', label: 'Javanese' },
  { value: 'ka', label: 'Georgian' },
  { value: 'kg', label: 'Kongo' },
  { value: 'ki', label: 'Kikuyu' },
  { value: 'kj', label: 'Kuanyama' },
  { value: 'kk', label: 'Kazakh' },
  { value: 'kl', label: 'Kalaallisut' },
  { value: 'km', label: 'Khmer' },
  { value: 'kn', label: 'Kannada' },
  { value: 'ko', label: 'Korean' },
  { value: 'kr', label: 'Kanuri' },
  { value: 'ks', label: 'Kashmiri' },
  { value: 'ku', label: 'Kurdish' },
  { value: 'kv', label: 'Komi' },
  { value: 'kw', label: 'Cornish' },
  { value: 'ky', label: 'Kyrgyz' },
  { value: 'la', label: 'Latin' },
  { value: 'lb', label: 'Luxembourgish' },
  { value: 'lg', label: 'Ganda' },
  { value: 'li', label: 'Limburgan' },
  { value: 'ln', label: 'Lingala' },
  { value: 'lo', label: 'Lao' },
  { value: 'lt', label: 'Lithuanian' },
  { value: 'lu', label: 'Luba-Katanga' },
  { value: 'lv', label: 'Latvian' },
  { value: 'mg', label: 'Malagasy' },
  { value: 'mh', label: 'Marshallese' },
  { value: 'mi', label: 'Maori' },
  { value: 'mk', label: 'Macedonian' },
  { value: 'ml', label: 'Malayalam' },
  { value: 'mn', label: 'Mongolian' },
  { value: 'mo', label: 'Moldovan' },
  { value: 'mr', label: 'Marathi' },
  { value: 'ms', label: 'Malay' },
  { value: 'mt', label: 'Maltese' },
  { value: 'my', label: 'Burmese' },
  { value: 'na', label: 'Nauru' },
  { value: 'nb', label: 'Norwegian Bokmål' },
  { value: 'nd', label: 'North Ndebele' },
  { value: 'ne', label: 'Nepali' },
  { value: 'ng', label: 'Ndonga' },
  { value: 'nl-be', label: 'Dutch (Belgium)' },
  { value: 'nl-nl', label: 'Dutch (Netherlands)' },
  { value: 'nl', label: 'Dutch' },
  { value: 'nn', label: 'Norwegian Nynorsk' },
  { value: 'no', label: 'Norwegian' },
  { value: 'nr', label: 'South Ndebele' },
  { value: 'nv', label: 'Navajo' },
  { value: 'ny', label: 'Chichewa' },
  { value: 'oc', label: 'Occitan' },
  { value: 'oj', label: 'Ojibwa' },
  { value: 'om', label: 'Oromo' },
  { value: 'or', label: 'Oriya' },
  { value: 'os', label: 'Ossetic' },
  { value: 'pa', label: 'Punjabi' },
  { value: 'pi', label: 'Pali' },
  { value: 'pl', label: 'Polish' },
  { value: 'ps', label: 'Pashto' },
  { value: 'pt-br', label: 'Portuguese (Brazil)' },
  { value: 'pt-pt', label: 'Portuguese (Portugal)' },
  { value: 'pt', label: 'Portuguese' },
  { value: 'qu', label: 'Quechua' },
  { value: 'rm', label: 'Romansh' },
  { value: 'rn', label: 'Rundi' },
  { value: 'ro-md', label: 'Romanian (Moldova)' },
  { value: 'ro', label: 'Romanian' },
  { value: 'ru', label: 'Russian' },
  { value: 'rw', label: 'Kinyarwanda' },
  { value: 'sa', label: 'Sanskrit' },
  { value: 'sc', label: 'Sardinian' },
  { value: 'sd', label: 'Sindhi' },
  { value: 'se', label: 'Northern Sami' },
  { value: 'sg', label: 'Sango' },
  { value: 'si', label: 'Sinhala' },
  { value: 'sk', label: 'Slovak' },
  { value: 'sl', label: 'Slovenian' },
  { value: 'sm', label: 'Samoan' },
  { value: 'sn', label: 'Shona' },
  { value: 'so', label: 'Somali' },
  { value: 'sq', label: 'Albanian' },
  { value: 'sr', label: 'Serbian' },
  { value: 'ss', label: 'Swati' },
  { value: 'st', label: 'Sotho' },
  { value: 'su', label: 'Sundanese' },
  { value: 'sv-fi', label: 'Swedish (Finland)' },
  { value: 'sv-se', label: 'Swedish (Sweden)' },
  { value: 'sv', label: 'Swedish' },
  { value: 'sw', label: 'Swahili' },
  { value: 'ta', label: 'Tamil' },
  { value: 'te', label: 'Telugu' },
  { value: 'tg', label: 'Tajik' },
  { value: 'th', label: 'Thai' },
  { value: 'ti', label: 'Tigrinya' },
  { value: 'tk', label: 'Turkmen' },
  { value: 'tl', label: 'Tagalog' },
  { value: 'tn', label: 'Tswana' },
  { value: 'to', label: 'Tonga' },
  { value: 'tr', label: 'Turkish' },
  { value: 'ts', label: 'Tsonga' },
  { value: 'tt', label: 'Tatar' },
  { value: 'tw', label: 'Twi' },
  { value: 'ty', label: 'Tahitian' },
  { value: 'ug', label: 'Uighur' },
  { value: 'uk', label: 'Ukrainian' },
  { value: 'ur', label: 'Urdu' },
  { value: 'uz', label: 'Uzbek' },
  { value: 've', label: 'Venda' },
  { value: 'vi', label: 'Vietlabelse' },
  { value: 'vo', label: 'Volapük' },
  { value: 'wa', label: 'Walloon' },
  { value: 'wo', label: 'Wolof' },
  { value: 'xh', label: 'Xhosa' },
  { value: 'yi', label: 'Yiddish' },
  { value: 'yo', label: 'Yoruba' },
  { value: 'za', label: 'Zhuang' },
  { value: 'zh-cn', label: 'Chinese (Simplified)' },
  { value: 'zh-tw', label: 'Chinese (Traditional)' },
  { value: 'zh', label: 'Chinese' },
  { value: 'zu', label: 'Zulu' },
];
